name: Build release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate POT
        uses: hivepress/action-generate-pot@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          composer install -o --no-dev
          npm install --omit=dev

      - name: Pack release
        run: |
          rm -rf .git* composer.* phpcs.xml package.json package-lock.json README.md
          cd ..
          zip -r release.zip ${{ github.event.repository.name }}

      - name: Upload release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ../release.zip
          asset_name: ${{ github.event.repository.name }}.zip
          asset_content_type: application/zip

  update-code-reference:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Build code reference
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: Build code reference
          repo: hivepress/code-reference
          token: ${{ secrets.PERSONAL_TOKEN }}
          ref: refs/heads/main
          inputs: '{ "version": "${{ github.event.release.tag_name }}" }'

  update-hook-reference:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Build hook reference
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: Build hook reference
          repo: hivepress/hook-reference
          token: ${{ secrets.PERSONAL_TOKEN }}
          ref: refs/heads/main

  update-api-reference:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: composer

      - name: Install Swagger
        run: composer require zircote/swagger-php

      - name: Generate OpenAPI
        run: vendor/bin/openapi . -e vendor -o openapi.yaml -l

      - name: Deploy documentation
        uses: bump-sh/github-action@v1
        with:
          doc: rest-api
          token: ${{ secrets.BUMP_TOKEN }}
          file: openapi.yaml
